version: "0.5"

processes:
  backend:
    command: "npm run dev"
    working_dir: "./backend"
    availability:
      restart: "on_failure"
      max_restarts: 5
    readiness_probe:
      http_get:
        host: localhost
        port: 3000
        path: /health
      initial_delay_seconds: 2
      period_seconds: 1
      timeout_seconds: 5
      success_threshold: 1
      failure_threshold: 3

  frontend:
    command: "npm run dev"
    working_dir: "./frontend"
    depends_on:
      backend:
        condition: process_healthy
    availability:
      restart: "on_failure"
      max_restarts: 5
    readiness_probe:
      http_get:
        host: localhost
        port: 5173
        path: /
      initial_delay_seconds: 3
      period_seconds: 1
      timeout_seconds: 5
      success_threshold: 1
      failure_threshold: 3

log_location: ./process-compose.log
log_level: info
